spring:
#  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?zeroDateTimeBehavior=ROUND&&serverTimezone=GMT%2B8
    username: root
    password: root
#zeroDateTimeBehavior=CONVERT_TO_NULL characte rEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
  pagehelper:
    dialect: mysql
    params: count=countSql
    reasonable: true
    support-methods-arguments: true
#  redis:
#    host: 127.0.0.1
#    port: 6379

logging:
  level:
    root: info
    com.shonan: debug
  file: log/blog-dev.log

#mybatis配置
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml


